<?php

$episodes = array(
	array("055", "Thursday", "War All The Time"),
	array("054", "Spiderbait", "Shashavaglava"),
	array("053", "Johnny Cash", "At San Quentin"),
	array("052", "Sufjan Stevens", "Illinois"),
	array("051", "The Mint Chicks", "Fuck The Golden Youth"),
	array("050", "American Football", "American Football"),
	array("049", "Haven", "Between The Senses"),
	array("048", "Foo Fighters", "Foo Fighters"),
	array("047", "Modern Giant", "Satellite Nights / This Is Sydney"),
	array("046", "Songs: Ohia", "Magnolia Electric Co."),
	array("045", "Metallica", "Metallica (The Black Album)"),
	array("044", "Cannibal Ox", "The Cold Vein"),
	array("043", "Nas", "Illmatic"),
	array("042", "Joanna Newsom", "The Milk-Eyed Mender"),
	array("041", "Modest Mouse", "The Lonesome Crowded West"),
	array("040", "Cru", "Da Dirty Thirty"),
	array("039", "Bruce Springsteen", "Born To Run"),
	array("038", "Spoon", "Girls Can Tell"),
	array("037", "Screeching Weasel", "My Brain Hurts"),
	array("036", "Real Estate", "Real Estate"),
	array("035", "TV On The Radio", "Desperate Youth, Blood Thirsty Babes"),
	array("034", "Spiritualized", "Ladies and Gentleman We Are Floating In Space"),
	array("033", "The National", "Sad Songs For Dirty Lovers"),
	array("032", "Black Rebel Motorcycle Club", "Howl"),
	array("031", "The Fiery Furnaces", "EP"),
	array("030", "Enya", "Watermark"),
	array("029", "Band Of Horses", "Everything All The Time"),
	array("028", "Liars", "Drum's Not Dead"),
	array("027", "Paul Simon", "Graceland"),
	array("026", "Land Of Talk", "Some Are Lakes"),
	array("025", "The Ataris", "Blue Skies, Broken Hearts... Next 12 Exits"),
	array("024", "Makaveli", "The Don Killuminati: The 7 Day Theory"),
	array("023", "Refused", "The Shape Of Punk To Come"),
	array("022", "D12", "Devil's Night"),
	array("021", "Neil Young", "Comes A Time"),
	array("020", "The Dandy Warhols", "Thirteen Tales From Urban Bohemia"),
	array("019", "Clor", "Clor"),
	array("018", "Eddie Vedder", "Into The Wild"),
	array("017", "Darkthrone", "Transilvanian Hunger"),
	array("016", "Deicide", "Deicide"),
	array("015", "M83", "Before The Dawn Heals Us"),
	array("014", "The Hold Steady", "Boys & Girls In America"),
	array("013", "Rage Against The Machine", "Evil Empire"),
	array("012", "Bloc Party", "Silent Alarm"),
	array("011", "The Replacements", "Let It Be"),
	array("010", "Jedi Mind Tricks", "Violent By Design"),
	array("009", "Woody Guthrie", "Dust Bowl Ballads"),
	array("008", "The Veils", "Nux Vomica"),
	array("007", "White Zombie", "Astro-Creep: 2000"),
	array("006", "The Smashing Pumpkins", "Siamese Dream"),
	array("005", "You Am I", "Hourly, Daily"),
	array("004", "Dustin Kensrue", "Please Come Home"),
	array("003", "Janet Jackson", "janet"),
	array("002", "Eric B. & Rakim", "Paid In Full"),
	array("001", "Nancy Sinatra", "Nancy & Lee")
);

?>